# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bujo < Formula
  desc "Terminal-based Bullet Journal tool"
  homepage "https://github.com/samakintunde/bujo"
  version "0.1.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.1/bujo_Darwin_x86_64.tar.gz"
      sha256 "962e6d1ba16e17e291c7a0cebdbb0523a13b36dc227e883e91cf58b008e634a8"

      def install
        bin.install "bujo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.1/bujo_Darwin_arm64.tar.gz"
      sha256 "23a152787c15b3a568fe28a592c4d0dbe548018e1c77259f4ea3edc1032f7407"

      def install
        bin.install "bujo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.1/bujo_Linux_x86_64.tar.gz"
      sha256 "aefc0428fe5c159eefa6027f2370d4051142e81447bde6125ee04a9e8a6b22bb"
      def install
        bin.install "bujo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.1/bujo_Linux_arm64.tar.gz"
      sha256 "dd0262072dfc659ed00dff6cc6a85707b3637ccd8f1fe6c5361c7ac0b7a40bd9"
      def install
        bin.install "bujo"
      end
    end
  end

  test do
    system "#{bin}/bujo version"
  end
end
