# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bujo < Formula
  desc "Terminal-based Bullet Journal tool"
  homepage "https://github.com/samakintunde/bujo"
  version "0.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.0/bujo_Darwin_x86_64.tar.gz"
      sha256 "d2335aceca2e5682fcb08e10b74afb812cb124db25bcbfac12832cbcd4e19578"

      def install
        bin.install "bujo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.0/bujo_Darwin_arm64.tar.gz"
      sha256 "fdf58f10dfa36ef90d9ac9fc229f31a5a692ca695f907ce55820925803dc3aef"

      def install
        bin.install "bujo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.0/bujo_Linux_x86_64.tar.gz"
      sha256 "bbbb8dc5cb478489b3d19aafea9a7f8a5a6f55eb1d7e2afcdc842fa65404b0a7"
      def install
        bin.install "bujo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samakintunde/bujo/releases/download/v0.1.0/bujo_Linux_arm64.tar.gz"
      sha256 "3fa5f7abad87d6a8d47bd3fa28560350983fc4693d8086cb769ec450fce95e56"
      def install
        bin.install "bujo"
      end
    end
  end

  test do
    system "#{bin}/bujo version"
  end
end
